version: '3'
services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile-ubuntu.base
    image: base-swift-ubuntu

  syslog:
    container_name: syslog
    build:
      context: .
      dockerfile: Dockerfile.syslog
    volumes:
      - /tmp/rsyslog-dev:/var/run/rsyslog/dev

  memcache:
    container_name: memcache
    image: memcached:alpine
    expose:
      - "11211"
    networks:
      swift_net:
        ipv4_address: 172.16.238.8

  proxy:
    image: "swift-proxy"
    depends_on:
      - base
      - syslog
      - memcache
    build:
      context: .
      dockerfile: ./Dockerfile.proxy
    ports:
      - "8080:8080/tcp"
    networks:
      swift_net:
        ipv4_address: 172.16.238.9
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - /tmp/rsyslog-dev/log:/dev/log

  account:
    image: "swift-account"
    depends_on:
      - base
      - syslog
    build:
      context: .
      dockerfile: ./Dockerfile.account
    expose:
      - "6202"
    networks:
      swift_net:
        ipv4_address: 172.16.238.10
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - "swiftdata:/srv/node/d1"
      - /tmp/rsyslog-dev/log:/dev/log

  container:
    image: "swift-container"
    depends_on:
      - base
      - syslog
    build:
      context: .
      dockerfile: ./Dockerfile.container
    expose:
      - "6102"
    networks:
      swift_net:
        ipv4_address: 172.16.238.11
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - "swiftdata:/srv/node/d1"
      - /tmp/rsyslog-dev/log:/dev/log

  object:
    image: "swift-object"
    depends_on:
      - base
      - syslog
    build:
      context: .
      dockerfile: ./Dockerfile.object
    expose:
      - "6002"
    networks:
      swift_net:
        ipv4_address: 172.16.238.12
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - "swiftdata:/srv/node/d1"
      - /tmp/rsyslog-dev/log:/dev/log


volumes:
  swiftdata:

networks:
  swift_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
