version: '3'
services:
  base-ubuntu:
    build:
      context: .
      dockerfile: ./Dockerfile-ubuntu.base
    image: base-swift-ubuntu

  # base-alpine:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile-alpine.base
  #   image: base-swift-alpine

  syslog:
    container_name: syslog
    build:
      context: .
      dockerfile: Dockerfile.syslog
    volumes:
      - /tmp/rsyslog-dev:/var/run/rsyslog/dev

  memcache:
    container_name: memcache
    image: memcached:alpine
    expose:
      - "11211"

  proxy:
    image: "swift-proxy"
    depends_on:
      - syslog
      - memcache
    build:
      context: .
      dockerfile: ./Dockerfile.proxy
    ports:
      - "8080:8080/tcp"
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - /tmp/rsyslog-dev/log:/dev/log

  account:
    image: "swift-account"
    depends_on:
      - syslog
    build:
      context: .
      dockerfile: ./Dockerfile.account
    expose:
      - "6202"
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - "swiftdata:/srv/node/d1"
      - /tmp/rsyslog-dev/log:/dev/log

  container:
    image: "swift-container"
    depends_on:
      - syslog
    build:
      context: .
      dockerfile: ./Dockerfile.container
    expose:
      - "6102"
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - "swiftdata:/srv/node/d1"
      - /tmp/rsyslog-dev/log:/dev/log

  object:
    image: "swift-object"
    depends_on:
      - syslog
    build:
      context: .
      dockerfile: ./Dockerfile.object
    expose:
      - "6002"
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - "swiftdata:/srv/node/d1"
      - /tmp/rsyslog-dev/log:/dev/log


volumes:
  swiftdata:
